name: Section C - Task 7 Deploy
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]   # add your custom label too if you set one

    env:
      AWS_PROFILE: default
      AWS_REGION: us-east-1
      SSH_PRIV_KEY: ~/.ssh/assignment2key

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Toolchain (awscli, terraform, ansible, jq)
        run: |
          set -euxo pipefail
          sudo apt-get update -y
          sudo apt-get install -y unzip jq python3-pip curl
          if ! command -v aws >/dev/null; then
            curl -fsSL https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
            unzip -q -o awscliv2.zip
            sudo ./aws/install --update
          fi
          aws --version
          TF_VERSION="1.9.8"
          if ! command -v terraform >/dev/null; then
            curl -fsSL "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip" -o tf.zip
            unzip -o tf.zip
            sudo mv -f terraform /usr/local/bin/terraform
          fi
          terraform -version
          pip install --user ansible
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Precheck: runner has valid AWS creds & SSH key
        run: |
          set -euo pipefail
          test -f ~/.aws/credentials || { echo "::error::.aws/credentials missing on runner"; exit 1; }
          test -f "${SSH_PRIV_KEY}"   || { echo "::error::SSH key ${SSH_PRIV_KEY} missing on runner"; exit 1; }
          if ! aws sts get-caller-identity >/dev/null 2>&1; then
            echo "::error::AWS credentials missing/expired on runner. Refresh ~/.aws/credentials and re-run."
            exit 1
          fi
          echo "AWS OK: $(aws sts get-caller-identity --query 'Arn' --output text)"

      - name: Make deploy.sh executable (safety)
        run: |
          sudo apt-get install -y dos2unix || true
          dos2unix ./deploy.sh || true
          chmod +x ./deploy.sh

      - name: Run deployment
        run: ./deploy.sh
