name: Section C - Task 7

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    env:
      AWS_PROFILE: default
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install prerequisites (jq, unzip, pip base, venv)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq unzip python3-venv curl gpg

      - name: Setup Python venv + Ansible
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install ansible
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Install Terraform
        run: |
          if ! command -v terraform >/dev/null 2>&1; then
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(. /etc/os-release; echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt-get update -y
            sudo apt-get install -y terraform
          fi
          terraform -version

      - name: Make deploy script executable
        run: chmod +x scripts/deploy.sh

      - name: Run deploy
        run: ./scripts/deploy.sh
