name: Section C - Task 7

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix line endings (safety)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y dos2unix
          dos2unix scripts/*.sh || true
          chmod +x scripts/deploy.sh

      - name: Install toolchain
        run: |
          sudo apt-get install -y jq unzip python3-pip curl gnupg
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible
          if ! command -v terraform >/dev/null 2>&1; then
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(. /etc/os-release; echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt-get update -y
            sudo apt-get install -y terraform
          fi
          terraform -version
          aws sts get-caller-identity || true  # sanity log

      - name: Run deploy (debug)
        env:
          TF_LOG: WARN
          TF_INPUT: "0"
        run: |
          set -euxo pipefail
          bash -x ./scripts/deploy.sh
