name: Section C - Task 7

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix line endings (safety)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y dos2unix
          dos2unix scripts/*.sh || true
          chmod +x scripts/deploy.sh

      - name: Install toolchain
        run: |
          set -euxo pipefail

          # Base packages
          sudo apt-get update -y
          sudo apt-get install -y jq unzip curl gnupg python3-pip

          # Ansible (avoid pip’s “externally-managed” warning)
          sudo apt-get install -y ansible

          # AWS CLI v2
          curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
          unzip -o awscliv2.zip
          sudo ./aws/install --update
          aws --version || true

          # Terraform
          if ! command -v terraform >/dev/null 2>&1; then
            curl -fsSL https://apt.releases.hashicorp.com/gpg \
              | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com \
              $(. /etc/os-release; echo $UBUNTU_CODENAME) main" \
              | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt-get update -y
            sudo apt-get install -y terraform
          fi
          terraform -version

      # >>> This replaces the IMDS step <<<
      - name: Configure AWS default profile from secrets
        env:
          AKID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SAK:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          STS:  ${{ secrets.AWS_SESSION_TOKEN }}
          REGION: ${{ env.AWS_REGION }}
        run: |
          set -euo pipefail
          mkdir -p ~/.aws
          {
            echo "[default]"
            echo "aws_access_key_id=${AKID}"
            echo "aws_secret_access_key=${SAK}"
            if [ -n "${STS:-}" ]; then
              echo "aws_session_token=${STS}"
            fi
          } > ~/.aws/credentials
          {
            echo "[default]"
            echo "region=${REGION:-us-east-1}"
          } > ~/.aws/config

          # Sanity check: should succeed now
          aws sts get-caller-identity --profile default

      - name: Run deploy (debug)
        env:
          TF_LOG: WARN
          TF_INPUT: "0"
        run: |
          set -euxo pipefail
          bash -x ./scripts/deploy.sh
