name: Section C - Task 7 Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]

    env:
      AWS_PROFILE: default
      AWS_REGION: us-east-1
      SSH_PRIV_KEY: /home/ubuntu/.ssh/assignment2key   # ← always use ubuntu's key

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Toolchain (awscli, terraform, ansible, jq)
        run: |
          set -euxo pipefail
          sudo apt-get update -y
          sudo apt-get install -y unzip jq curl python3-pip
          # AWS CLI v2
          if ! command -v aws >/dev/null; then
            curl -fsSL https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
            unzip -q -o awscliv2.zip
            sudo ./aws/install --update
          fi
          aws --version
          # Terraform
          TF_VERSION="1.9.8"
          if ! command -v terraform >/dev/null; then
            curl -fsSL "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip" -o tf.zip
            unzip -o tf.zip
            sudo mv -f terraform /usr/local/bin/terraform
          fi
          terraform -version
          # Ansible from apt (avoids PEP 668)
          sudo apt-get install -y ansible

      - name: Debug, show ubuntu SSH dir
        run: |
          ls -la /home/ubuntu/.ssh || true

      - name: Precheck, runner has valid AWS creds & SSH key (ubuntu path)
        shell: bash
        run: |
          set -euo pipefail
          if [ ! -f "/home/ubuntu/.aws/credentials" ] && [ ! -f "$HOME/.aws/credentials" ]; then
            echo "::error::.aws/credentials missing on runner (tried /home/ubuntu and \$HOME)"; exit 1
          fi
          if [ ! -f "${SSH_PRIV_KEY}" ]; then
            echo "::error::SSH key ${SSH_PRIV_KEY} missing on runner"; exit 1
          fi
          # permissions sanity (won’t fail if already correct)
          chmod 700 /home/ubuntu/.ssh 2>/dev/null || true
          chmod 600 "${SSH_PRIV_KEY}" 2>/dev/null || true
          if ! aws sts get-caller-identity >/dev/null 2>&1; then
            echo "::error::AWS credentials missing/expired on runner. Refresh /home/ubuntu/.aws/credentials and re-run."
            exit 1
          fi
          echo "AWS OK: $(aws sts get-caller-identity --query 'Arn' --output text)"
          echo "SSH key OK at ${SSH_PRIV_KEY}"

      - name: Make deploy.sh executable (safety)
        run: |
          sudo apt-get install -y dos2unix || true
          dos2unix ./deploy.sh || true
          chmod +x ./deploy.sh

      - name: Run deployment
        run: ./deploy.sh

      - name: Run deployment
        run: ./deploy.sh
